### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by publicENEMY** [stilldesign/PhysX.Net#16]
Im unable to compile both PhysX.Net and PhysX.Net-3.3. I have cloned nvidia physx and successfully compiled it. 

What are the steps to compile both libraries?

**Comment by stilldesign** [comment]
From the *master* branch?

What errors are coming up when you build PhysX.Net?

In short; clone the repo, download and extract the PhysX SDK to the default location below and it should build successfully after that
PhysX SDK dir: C:\Program Files (x86)\NVIDIA Corporation\NVIDIA PhysX SDK\3.3.1

**Comment by publicENEMY** [comment]
Will try that and report back. Thank you.

**Comment by publicENEMY** [comment]
Unsuccessful. Here are the errors

Error	2	error C2248: 'physx::PxControllerDesc::PxControllerDesc' : cannot access protected member declared in class 'physx::PxControllerDesc'	e:\Users\iJam\Source\Repos\PhysX.Net\PhysX.Net-3.3\PhysX.Net-3\Source\BoxControllerDesc.cpp	41	1	PhysX.Net
Error	3	error C2248: 'physx::PxControllerDesc::PxControllerDesc' : cannot access protected member declared in class 'physx::PxControllerDesc'	e:\Users\iJam\Source\Repos\PhysX.Net\PhysX.Net-3.3\PhysX.Net-3\Source\CapsuleControllerDesc.cpp	41	1	PhysX.Net
Error	4	error C2039: 'D3D9_INTEROP' : is not a member of 'physx::PxCudaInteropMode' (Source\CudaContextManager.cpp)	e:\users\ijam\source\repos\physx.net\physx.net-3.3\physx.net-3\source\CudaEnum.h	8	1	PhysX.Net
Error	5	error C2065: 'D3D9_INTEROP' : undeclared identifier (Source\CudaContextManager.cpp)	e:\users\ijam\source\repos\physx.net\physx.net-3.3\physx.net-3\source\CudaEnum.h	8	1	PhysX.Net
Error	6	error C3766: 'PhysX::CudaContextManager' must provide an implementation for the interface method 'void PhysX::IDisposable::OnDisposing::add(System::EventHandler ^)' (Source\CudaContextManager.cpp)	e:\users\ijam\source\repos\physx.net\physx.net-3.3\physx.net-3\source\CudaContextManager.h	147	1	PhysX.Net
Error	7	error C3766: 'PhysX::CudaContextManager' must provide an implementation for the interface method 'void PhysX::IDisposable::OnDisposing::remove(System::EventHandler ^)' (Source\CudaContextManager.cpp)	e:\users\ijam\source\repos\physx.net\physx.net-3.3\physx.net-3\source\CudaContextManager.h	147	1	PhysX.Net
Error	8	error C3766: 'PhysX::CudaContextManager' must provide an implementation for the interface method 'void PhysX::IDisposable::OnDisposed::add(System::EventHandler ^)' (Source\CudaContextManager.cpp)	e:\users\ijam\source\repos\physx.net\physx.net-3.3\physx.net-3\source\CudaContextManager.h	147	1	PhysX.Net
Error	9	error C3766: 'PhysX::CudaContextManager' must provide an implementation for the interface method 'void PhysX::IDisposable::OnDisposed::remove(System::EventHandler ^)' (Source\CudaContextManager.cpp)	e:\users\ijam\source\repos\physx.net\physx.net-3.3\physx.net-3\source\CudaContextManager.h	147	1	PhysX.Net
Error	11	error C3766: 'PhysX::Foundation' must provide an implementation for the interface method 'void PhysX::IDisposable::OnDisposing::add(System::EventHandler ^)' (Source\CudaContextManager.cpp)	e:\users\ijam\source\repos\physx.net\physx.net-3.3\physx.net-3\source\Foundation.h	56	1	PhysX.Net
Error	12	error C3766: 'PhysX::Foundation' must provide an implementation for the interface method 'void PhysX::IDisposable::OnDisposing::remove(System::EventHandler ^)' (Source\CudaContextManager.cpp)	e:\users\ijam\source\repos\physx.net\physx.net-3.3\physx.net-3\source\Foundation.h	56	1	PhysX.Net
Error	13	error C3766: 'PhysX::Foundation' must provide an implementation for the interface method 'void PhysX::IDisposable::OnDisposed::add(System::EventHandler ^)' (Source\CudaContextManager.cpp)	e:\users\ijam\source\repos\physx.net\physx.net-3.3\physx.net-3\source\Foundation.h	56	1	PhysX.Net
Error	14	error C3766: 'PhysX::Foundation' must provide an implementation for the interface method 'void PhysX::IDisposable::OnDisposed::remove(System::EventHandler ^)' (Source\CudaContextManager.cpp)	e:\users\ijam\source\repos\physx.net\physx.net-3.3\physx.net-3\source\Foundation.h	56	1	PhysX.Net
Error	16	error C3766: 'PhysX::GpuDispatcher' must provide an implementation for the interface method 'void PhysX::IDisposable::OnDisposing::add(System::EventHandler ^)' (Source\CudaContextManager.cpp)	e:\users\ijam\source\repos\physx.net\physx.net-3.3\physx.net-3\source\GpuDispatcher.h	72	1	PhysX.Net
Error	17	error C3766: 'PhysX::GpuDispatcher' must provide an implementation for the interface method 'void PhysX::IDisposable::OnDisposing::remove(System::EventHandler ^)' (Source\CudaContextManager.cpp)	e:\users\ijam\source\repos\physx.net\physx.net-3.3\physx.net-3\source\GpuDispatcher.h	72	1	PhysX.Net
Error	18	error C3766: 'PhysX::GpuDispatcher' must provide an implementation for the interface method 'void PhysX::IDisposable::OnDisposed::add(System::EventHandler ^)' (Source\CudaContextManager.cpp)	e:\users\ijam\source\repos\physx.net\physx.net-3.3\physx.net-3\source\GpuDispatcher.h	72	1	PhysX.Net
Error	19	error C3766: 'PhysX::GpuDispatcher' must provide an implementation for the interface method 'void PhysX::IDisposable::OnDisposed::remove(System::EventHandler ^)' (Source\CudaContextManager.cpp)	e:\users\ijam\source\repos\physx.net\physx.net-3.3\physx.net-3\source\GpuDispatcher.h	72	1	PhysX.Net
Error	21	error C2259: 'PhysX::GpuDispatcher' : cannot instantiate abstract class	e:\Users\iJam\Source\Repos\PhysX.Net\PhysX.Net-3.3\PhysX.Net-3\Source\CudaContextManager.cpp	20	1	PhysX.Net
Error	22	error C2039: 'D3D9_INTEROP' : is not a member of 'physx::PxCudaInteropMode' (Source\GpuDispatcher.cpp)	e:\users\ijam\source\repos\physx.net\physx.net-3.3\physx.net-3\source\CudaEnum.h	8	1	PhysX.Net
Error	23	error C2065: 'D3D9_INTEROP' : undeclared identifier (Source\GpuDispatcher.cpp)	e:\users\ijam\source\repos\physx.net\physx.net-3.3\physx.net-3\source\CudaEnum.h	8	1	PhysX.Net
Error	24	error C3766: 'PhysX::CudaContextManager' must provide an implementation for the interface method 'void PhysX::IDisposable::OnDisposing::add(System::EventHandler ^)' (Source\GpuDispatcher.cpp)	e:\users\ijam\source\repos\physx.net\physx.net-3.3\physx.net-3\source\CudaContextManager.h	147	1	PhysX.Net
Error	25	error C3766: 'PhysX::CudaContextManager' must provide an implementation for the interface method 'void PhysX::IDisposable::OnDisposing::remove(System::EventHandler ^)' (Source\GpuDispatcher.cpp)	e:\users\ijam\source\repos\physx.net\physx.net-3.3\physx.net-3\source\CudaContextManager.h	147	1	PhysX.Net
Error	26	error C3766: 'PhysX::CudaContextManager' must provide an implementation for the interface method 'void PhysX::IDisposable::OnDisposed::add(System::EventHandler ^)' (Source\GpuDispatcher.cpp)	e:\users\ijam\source\repos\physx.net\physx.net-3.3\physx.net-3\source\CudaContextManager.h	147	1	PhysX.Net
Error	27	error C3766: 'PhysX::CudaContextManager' must provide an implementation for the interface method 'void PhysX::IDisposable::OnDisposed::remove(System::EventHandler ^)' (Source\GpuDispatcher.cpp)	e:\users\ijam\source\repos\physx.net\physx.net-3.3\physx.net-3\source\CudaContextManager.h	147	1	PhysX.Net
Error	29	error C3766: 'PhysX::GpuDispatcher' must provide an implementation for the interface method 'void PhysX::IDisposable::OnDisposing::add(System::EventHandler ^)' (Source\GpuDispatcher.cpp)	e:\users\ijam\source\repos\physx.net\physx.net-3.3\physx.net-3\source\GpuDispatcher.h	72	1	PhysX.Net
Error	30	error C3766: 'PhysX::GpuDispatcher' must provide an implementation for the interface method 'void PhysX::IDisposable::OnDisposing::remove(System::EventHandler ^)' (Source\GpuDispatcher.cpp)	e:\users\ijam\source\repos\physx.net\physx.net-3.3\physx.net-3\source\GpuDispatcher.h	72	1	PhysX.Net
Error	31	error C3766: 'PhysX::GpuDispatcher' must provide an implementation for the interface method 'void PhysX::IDisposable::OnDisposed::add(System::EventHandler ^)' (Source\GpuDispatcher.cpp)	e:\users\ijam\source\repos\physx.net\physx.net-3.3\physx.net-3\source\GpuDispatcher.h	72	1	PhysX.Net
Error	32	error C3766: 'PhysX::GpuDispatcher' must provide an implementation for the interface method 'void PhysX::IDisposable::OnDisposed::remove(System::EventHandler ^)' (Source\GpuDispatcher.cpp)	e:\users\ijam\source\repos\physx.net\physx.net-3.3\physx.net-3\source\GpuDispatcher.h	72	1	PhysX.Net

**Comment by publicENEMY** [comment]
I cloned latest physx library. Here are the screenshot of C:\Program Files (x86)\NVIDIA Corporation\NVIDIA PhysX SDK\3.3.1

Im aware that the version i use is 3.3.3.

![image](https://cloud.githubusercontent.com/assets/2562219/8130450/fef6094c-1144-11e5-9201-a4a0f05de62a.png)

**Comment by publicENEMY** [comment]
I have successfully compiled physx.net

My problem was im using the latest version of physx(cloned github). After changed to physx v3.3.1, all problems gone.

By the way, are you planning to update to latest version of physx or not in the near future?

Thanks.

**Comment by publicENEMY** [comment]
Unfortunately, I spoke too soon. While I am able to build the samples without problem, Im unable to run the built sample. Tested one of the sample, RigidBodySample, and here are the error received.

System.BadImageFormatException was unhandled
Message: An unhandled exception of type 'System.BadImageFormatException' occurred in mscorlib.dll
Additional information: Could not load file or assembly 'PhysX.Net, Version=0.3.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.

**Comment by rlouden-irl** [comment]
It could be an issue with the wrong build. I know that the samples use the x86 version of the DLL,

Also, make sure that the following assemblies are located in the same directory as the executable:
- nvToolsExt86_1.dll
- PhysX3CharacterKinematicCHECKED_x86.dll
- PhyX3CHECKED_x86.dll
- PhysX3CommonCHECKED_x86.dll
- PhysX3CookingCHECKED_x86.dll
- PhysX3GpuCHECKED_x86.dll

**Comment by publicENEMY** [comment]
You were right rlouden-irl. Changing the build to x86 worked. I guess, x64 needs manual tweaking.

Thanks.

**Comment by rlouden-irl** [comment]
Not a problem!

The x64 assembly should work just fine. The samples specifically target x86.
