### ISSUE TITLE
Cannot get SimulationEventCallback events to fire.

### ISSUE THREAD

**Issue by AnderT** [stilldesign/PhysX.Net#17]
Hi Chad,

I do not seem to be able get any contact events to fire. I have read that I need to possibly supply a FilterShader, but sceneDesc.filterShader is not implemented as far as I can see.

Can you please let me know if I am doing something wrong and if not, do you have plans to implement this functionality?

Thanks again for all the work you have put into this wrapper.

Cheers,

Ander

**Comment by stilldesign** [comment]
Hey,
This was a hot topic recently for a few people, contact events don't work on the master branch, but I've implemented it a branch:
https://github.com/stilldesign/PhysX.Net/tree/SimulationEventCallback

I need to get round to cleaning it up and merging it back into master

**Comment by AnderT** [comment]
Awesome : )

I noticed the branch momments after I posted!

Cheers mate, thanks again.

Ander

**Comment by stilldesign** [comment]
Just going round cleaning a few things up - this has been merged into the master branch

**Comment by AnderT** [comment]
Awesome : )

Cheers mate.

**Comment by AnderT** [comment]
Hi Chad,

I have now upgraded to the latest build, but still can not receive contact events. I can get constraint events to work fine and have set the group in the DefaultFilterShader, but dice : (

Amy thoughts?

**Comment by stilldesign** [comment]
It shouldn't be anything more than setting the scene.SetSimulationEventCallback callback. I made a sample to demonstrate contact callbacks.

**Comment by AnderT** [comment]
I used your test code from the contact modify test, just modified it a little for OnContact.

![image](https://cloud.githubusercontent.com/assets/11612389/11501397/db559208-9887-11e5-9998-154f23b0e595.png)

Looks like it should work, but still no luck.

**Comment by stilldesign** [comment]
Hey, not sure if you've solved this one yet, but what's needed is setting the FilterShader on the scene description.

```csharp
var sd = new SceneDesc();
sd.FilterShader = new SampleFilterShader();

...

public class SampleFilterShader : SimulationFilterShader
{
	public override FilterResult Filter(int attributes0, FilterData filterData0, int attributes1, FilterData filterData1)
	{
		return new FilterResult
		{
			FilterFlag = FilterFlag.Default,
			// Cause PhysX to report any contact of two shapes as a touch and call SimulationEventCallback.OnContact
			PairFlags = PairFlag.ContactDefault | PairFlag.NotifyTouchFound | PairFlag.NotifyTouchLost
		};
	}
}
```

This one actually confused me for a little bit, because in my samples I set the FilterShader in a base class so it's kind of hidden away and not super obvious, I'll update my samples to make it a bit more obvious :)

**Comment by AnderT** [comment]
YaY!!!!

Awesome : ) Working like a charm : )

Thanks mate, I really appreciate your help. 

Ander

**Comment by stilldesign** [comment]
:+1:
