### ISSUE TITLE
Cannot run compiled file-Missing dependencies (USING WINDOW 10)

### ISSUE THREAD

**Issue by thunguyenphuoc** [stilldesign/PhysX.Net#20]
Hello,
I wrote a very simple bounding box scene just to test the workflow (I use Nuget to get the package and dependencies). I can compile the file but when I run the file it gives out the error of:

"An unhandled exception of type 'System.IO.FileNotFoundException' occurred in mscorlib.dll

Additional information: Could not load file or assembly 'PhysX.Net.dll' or one of its dependencies. The specified module could not be found."

I'm using window 10 64 bit, Visual Studio 2015.

Any thoughts on this?

Regards

**Comment by stilldesign** [comment]
Hey,
The nuget package should install the few required native PhysX DLLs to enable PhysX.Net to run, so it's probably some other missing DLL. To debug these kinds of missing file exceptions - you'll need to use the fusion log viewer

Fuslogvw.exe is in the Windows SDK:
C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6 Tools\FUSLOGVW.exe

To enable it:
http://stackoverflow.com/questions/255669/how-to-enable-assembly-bind-failure-logging-fusion-in-net

**Comment by AnderT** [comment]
Hi,
I had the same problem after upgrading to 2015 RTM. Did some digging with Procmon and noticed the following DLLs could not be found;

msvcp120d.dll
msvcr120d.dll

I had to revert to the preview and copy the DLLs. I dropped them into my output directory and now all is good, even after upgrading again. I have attached a zip containing them, you will need to change the extension to zip.

[MissingDLLs.txt](https://github.com/stilldesign/PhysX.Net/files/41521/MissingDLLs.txt)

Ander

**Comment by thunguyenphuoc** [comment]
Hi Chad @stilldesign ,
Thank you for your reply. I followed your advice and try to find the missing dll but didn't succeed, but seems like @AnderT has found the solution. I will have a look into them. Thank you to you both.
Thu

**Comment by stilldesign** [comment]
Hi,
Good to hear :) Yes, PhysX.Net.dll is currently in VS2013 (which is v12) and the nuget package installs the debug version of PhysX.Net.dll which in-tern uses the debug version of the C++ runtime, hence why it's looking for msvcp120d and msvcr120d.

I should update the solution and nuget package to 2015 at some point :)

**Comment by AnderT** [comment]
Hi Thu,

Very happy to have been able to help : )
