### ISSUE TITLE
Compile issue of PhysX.Net-3.3 (VS2015 and PhysX 3.3.4)

### ISSUE THREAD

**Issue by amoonfana** [stilldesign/PhysX.Net#23]
Hi stilldesign,

I downloaded PhysX 3.3.4 and complied it under 'checked' and 'x64' environment in the VS2015. After that, I downloaded PhysX.Net-3.3 (VS2015 and PhysX 3.3.4)  trying to compile it. But I ended up with many of this errors.

> 'Error LNK2038 mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value MD_DynamicRelease'

I have googled it and it seems because the PhysX 3.3.4 Runtime Library is set to ‘Multi-threaded (/MT)’ but PhysX.Net is set to 'Multi-threaded DLL (/MD)'.

Thus, how can I fix this error? I have stupidly just tried to switch their Runtime Library to different settings but didn't work.

With thanks.

**Comment by stilldesign** [comment]
Changing PhysX to /MD is how I use PhysX with PhysX.Net. I have a fork of PhysX here: https://github.com/stilldesign/PhysX-3.3.

I don't truly understand why this is required, or how to allow PhysX to be used as-is. For now I just use my fork.

**Comment by amoonfana** [comment]
Thanks so much for your reply.

Now the PhysX.Net can be compiled successfully. However, all the samples will collapse while rendering (It seems VehicleSample is normal and has no rendering part). I am a beginner of PhysX and DirectX, thus I don't know what happened but I can basically guess PhysX.Net is normal at the moment. Below is the error report of all collapsed samples for your reference (All of them have just one error).

>Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
     at SharpDX.Direct3D11.DeviceContexxt.Draw(Int32 vertexCount, Int32 startVertexLocation)
     at PhysX.Samples.Engine.Engine.DrawVertices(VertexPositionColor[] vertices, PromitiveTopology top) in D:\GitHubLibrary\c#PhysX\PhysX.Net\PhysX.Net-3.3\Samples\Engine\Engine\Engine.cs: Line: 360
     etc...

Thank you again for your help and PhysX.Net.

**Comment by stilldesign** [comment]
The Vehicle sample was never finished, just don't have enough free time.
The other samples should work fine however
