### ISSUE TITLE
Collision Filtering already working?

### ISSUE THREAD

**Issue by Jack43174** [stilldesign/PhysX.Net#26]
Hi,

I want to do custom Collision Filtering and I am unsure if that is meant to work already. I saw a unit test (ContactModifyCallbackTest.cs) in the sources, but it also states "Not finished yet".

Is just the test code not finished yet or is there still work to do in PhysX.Net?
If Collision Filtering is already available I'd be very thankful for a little piece of example code.

Thanks

**Comment by stilldesign** [comment]
I'd say there's still work to do on getting collision filtering working. Not sure how tricky or how much more work is involved though

**Comment by Jack43174** [comment]
Well, after adding `PairFlag.ModifyContacts` to the (Sample)FilterShader, I got the ContactModifyCallback working! The contacts are reported and can be modified. I guess the term "shader" is misleading as the code won't be executed on the GPU anyway.

I could not get the DefaultFilterShader working. As far as I understood, that one should be used if no user-defined SimulationFilterShader is defined for the scene. I guess that internal DefaultFilterShader does not specify the `PairFlag.ModifyContacts`.

 There seem to be still some fields missing in the wrapper, e.g. for the filter variables (PxGet/SetFilterBool, PxPxGet/setFilterConstants), but I don't know how useful this DefaultFilterShader is anyway.

I think I can now write my own SimulationFilterShader that takes the actors' group ID into account. Something like the original `PxDefaultSimulationFilterShader`

Thanks a lot.
