### ISSUE TITLE
3.4 Scene Flags

### ISSUE THREAD

**Issue by AnderT** [stilldesign/PhysX.Net#29]
Hi Chad,

How's life? All good I hope : )

Just trying to move to 3.4, but cannot seem to get GPU acceleration working.
**Enable_GPU_Dynamics** seems to be missing.

Ander

**Comment by stilldesign** [comment]
Hey,
Haven't had a chance to look at the new GPU rigid body stuff just yet, I'm currently upgrading my 3D engine to use 3.4, it's still on 2.8 haha, thought it was about time

`Enable_GPU_Dynamics` is missing from SceneFlag, I'll add the missing enum values in shortly.

If you want to use it right now, try `(SceneFlag)(1 << 19)`.
(You'll need to configure the a GPU dispatcher as well to get GPU physics running)

**Comment by AnderT** [comment]
Hi Chad,

Thanks for the quick reply : )

Dim cudaContexManager = New CudaContextManager(mPhysics.Foundation) is throwing;
**System.Exception: 'GPU PhysX isn't available in VS2015 :( We'll have to wait till NVIDIA get this working'**

**Comment by stilldesign** [comment]
Ah right, I'll need to remove that, GPU wasn't available in previous versions whilst using VS2015, so I put that in there as otherwise it just caused some weird error.
I'll also need to finish off CudaContextManager now that GPU rigid bodies are possible.

**Comment by AnderT** [comment]
No worries : )

I will hold off for a bit.

Cheers mate : )

**Comment by stilldesign** [comment]
I've made a couple of changes and enabled GPU physics for the samples - as far as I can they're running on the GPU. Unfortunately the memory usage has gone from around 55MB to 700MB with GPU enabled :'( So not sure what that's all about. And on top of that the samples seem to run a lot slower, really laggy. I'm sure there's probably something really obviously dumb I've done that's causing this, but I'll have to hunt for that later.

The samples use the GPU by default now. If GPU physics isn't available - either the user doesn't have a suitable graphics card or they have 'PhysX settings' turned to 'CPU' in the NVIDIA Control Panel, then it'll just default back to CPU with a warning emitted to the console.

**Comment by AnderT** [comment]
Hi Chad,

I have run an Update-Package, but no change. Did you have any luck working out why it is slower?

**Comment by stilldesign** [comment]
Hey, I haven't got round to building/publishing an updated nuget package for 3.4 (latest one is for 3.3.4). You'd need to grab the source code and the PhysX34 branch. I could probably publish one for 3.4 tonight, it's all pretty easy, it's all scripted.

Unfortunately I don't have a clue why it's so slow, bit of a shame. I might have to ask on the NVIDIA forums, see if someone has a bright idea. I'm sure it'll just be something small causing it.

**Comment by AnderT** [comment]
Hi Chad, I have never been good with getting the source to build, have cloned the repository but get a bunch of errors when I try building. I am the type who is scared by C++ : ) Any pointers would be great, seems there are some headers missing.

**Comment by stilldesign** [comment]
Just pushed up a build/nuget package of a build of the 3.4 branch, give it a try

https://www.nuget.org/packages/PhysX.Net/
Install-Package PhysX.Net -Pre

**Comment by AnderT** [comment]
Getting 0.2 frames a second : (

Scene.FetchResults is taking around 500ms every second step.

**Comment by AnderT** [comment]
Hi Chad,
Sorry to bother you, but I was wondering if you had had any joy with the slowdown. Seems unusable at the moment : (
Cheers,
Ander

**Comment by stilldesign** [comment]
Hey, unfortunately I haven't touched this issue in a while now as I just don't have a clue what could be causing it. I've got some time off work shortly, so I'll have another crack at though.

**Comment by AnderT** [comment]
Hi Chad,
Happy New Year : ) Hope you have a great one!
Cheers,
Ander

**Comment by AnderT** [comment]
Hey Chad,
Did you ever get a chance to have a quick look?
Cheers,
Ander

**Comment by steenhother** [comment]
Hi Chad

We have been using PhysX 3.4 for some years now.

You have created and maintained a .Net wrapper for the current version (3.4)… and then I want to ask you if you could be interested in helping our company creating a new wrapper for the new version released by Nvidia the 20th of December.
I have a developer that can do some of it but I thing it would be necessary to have an expert to help us (at least to speed up the process)

We are not interested in all aspect of the PhysX engine… it is mostly the rigid parts and joints – at least that is the first things that should be covered by the wrapper.

Hope you could be interested and if yes when we can find a way to pay you on some kind of consultancy agreement. 

Best Regards
CTO, Steen Hother Jensen
Xcelgo, shj@xcelgo.com

**Comment by stilldesign** [comment]
Hi,
I managed to find some free time, so I've spent a few hours and updated the wrapper to 4.0.0: https://github.com/stilldesign/PhysX.Net/tree/PhysX40

It wasn't too hard to update to v4 luckily. Updating from 3.3 to 3.4 was much harder. Most of the work was just getting PhysX itself to compile, then removing classes and methods which have now been removed in PhysX itself (like Particles and Cloth).

**Comment by AnderT** [comment]
Hi Chad,

Thanks for getting the 4.0 wrapper out so fast : ) I am having a couple of issues though, and was wondering if you had had similar. 

First, after updating my code "Scene.FetchResults(True)" takes an age.
Second, I cannot find SceneDesc.SolverType.

Cheers,

Ander

**Comment by stilldesign** [comment]
Hey,
I had missed `SolverType` - I've added that in now, though it does seem to make the samples run a little bit slower (not too bad though)

The RigidBodiesSample runs happily on my modest laptop. The frame rate seems just fine, almost to the point where the basic `Simulate(elapsedTime)` code is running too fast. I'll see how it runs on my desktop computer when I'm back home.

Looks like I didn't handle adding the newly created Shape to the `RigidActor.Shapes` collection when calling `CreateExclusiveShape` - I'll look into this.

**Comment by AnderT** [comment]
Hey Chad,

Thanks so much for looking at this so fast : )

When I run my simulation with 3.4, fetchresults is taking less than 1ms. With 4.0 it takes 10ms. I will try setting something up from scratch and see if it is specific to what I am doing.

Will let you know how I go.

Cheers,

Ander

**Comment by AnderT** [comment]
Hi Chad,

I cannot seem to get PhysX 4.1 to compile. When I run generate_projects.bat, nothing happens : (

Do you have any pointers?

Cheers,

Ander

**Comment by AnderT** [comment]
Hey Chad,

I was wondering if you are thinking of sharing StillEngine?

It looks like exactly what I am looking for.

Cheers,

Ander

**Comment by stilldesign** [comment]
Hey,
hehe StillEngine is just my personal 3D engine, I use it to learn and play. Anything it can do, Unity and Unreal engines can do better and faster. If I were employed or seriously looking at making a game I wouldn't use my engine I'd only use Unity or Unreal. They've been tested in the real world and had millions of dollar spent on them. Mines just a personal hobby thing.

I still do spend a bit of time on it, recently I've added some post-process effects; color grading, desaturate and vignetting :) I need to finish off my parallel split shadow map shader after those

**Comment by AnderT** [comment]
Hi Chad,

I am also just working on a personal project, and I think that is why StillEngine maybe a good fit.

I do not need lots of bells and whistles, just a simple renderer and maybe some post-process to make it look nice. Also, it being C# means I could drop it into my project with little effort.

Anyway it was just a thought : ) And as ever, thanks for PhysX.Net!

Cheers,

Ander

**Comment by AnderT** [comment]
Hey Chad,

I have managed to compile PhysX 4.1 and PhysX.Net : )

Seems it is still not adding the shape to Shapes. I have had a look at the code and am a wee bit lost.

Cheers,

Ander

**Comment by stilldesign** [comment]
Hey, looks like I missed adding the `Shape` instance to the `RigidActor.Shapes` after calling `RigidActorExt.CreateExclusiveShape`. I'll try get this added tonight.

**Comment by AnderT** [comment]
Cool : ) Thanks for looking at this : )

I have mangaged to get it working, but probably in a bad way!
