### ISSUE TITLE
Does nuget have any release version of physx.net?

### ISSUE THREAD

**Issue by justinuliu** [stilldesign/PhysX.Net#30]
Hi,

   I was wondering if I could get a last release version of PhysX.Net somewhere ?

**Comment by stilldesign** [comment]
Hi,
There's the nuget command on the homepage and if you search nuget.org for physx it comes right up :)

The current version is tagged as alpha, so to install you'll need the -Prerelease argument.
This package contains the DLL for PhysX.Net for 3.4.0 of PhysX and the required native runtime files.

https://www.nuget.org/packages/PhysX.Net/0.7.3-alpha

**Comment by justinuliu** [comment]
I'm so sorry I didn't make myself clear.  What I mean is I wonder if I could get a Release version for Physx.Net,  not the Debug version. I found that DLLs of PhyX are all suffix with "DEBUG".
  Please correct me, if I am wrong.

**Comment by stilldesign** [comment]
Ah I see, atm I've only made a debug package.
There is a release configuration in the source code which uses the release dlls, so if you're feeling brave you could build that, but it is a bit tricky to setup.

I'll try find some time to create a release nuget package for you.

**Comment by justinuliu** [comment]
I can build it myself.   
Thank you.

This is a great project.

**Comment by adobroradnikh** [comment]
[PhysXnet64.zip](https://github.com/stilldesign/PhysX.Net/files/1296426/x64.zip)
