### ISSUE TITLE
RigidDynamic Lock Flags Missing

### ISSUE THREAD

**Issue by Pysassin** [stilldesign/PhysX.Net#32]
Could we get the RigidDynamicLockFlags integrated? They are used to stop physics from changing a linear or angular axis of movement. Looks like the call is RigidDynamic.setLockFlags.

**Comment by stilldesign** [comment]
Hi,
`RigidDynamicLockFlags` should be in there (v0.10.0-alpha).
It can be used on a `RigidDynamic` instance, e.g.:

![image](https://user-images.githubusercontent.com/4223821/37124647-0c35ee5e-22ce-11e8-8b11-d81f58c81985.png)

**Comment by Pysassin** [comment]
Can I assume this is the NuGet prerelease version? I had it installed to check on the delete shape methods but hadn't even bothered to check the flags. Will pull it in and check.

**Comment by Pysassin** [comment]
Could very well be a lacking on my part but when I install the alpha prerelease nuget package references are not added. I cannot seem to manually add them to the project either. I get errors when trying to.

**Comment by stilldesign** [comment]
Hi,
I just tried installing the 0.10.0 of the package by;

- Creating a new (C# .NET 4.7) project
- Ran `Install-Package -Prerelease PhysX.Net`
- Tested to see if I could create a new `Foundation` class instance

And that's all seemed to work

What error are you seeing?
