### ISSUE TITLE
HI how to compile the Physx3.4 on PS4 platform ? 

### ISSUE THREAD

**Issue by wavebbs** [stilldesign/PhysX.Net#33]
HI, we use physX3.4  in our projects, so We need to compile physX3.4 that supported to PS4 . In order to run our project on PS4 platform.  
We need the dynamic lib which with ".prx" .
But I don't know how to compile it?  Does anyone know it?

**Comment by stilldesign** [comment]
I can't imagine you can run the .NET framework on the PS4 and thus not this project.
PhysX itself can run on the PlayStation, you'll want to go this issue on the NVIDIA forums though.

**Comment by wavebbs** [comment]
Thank you for answering me!  Actually， we just use our PhysX engine to instead of the Unity3D's,  because we want to have the same physical calculate result on Client and Server. So we use our physX engine on client and server.   So we need to get the Physx  lib run on PS4.
