### ISSUE TITLE
How to compile to mono/linux? It is possible?

### ISSUE THREAD

**Issue by MagistrAVSH** [stilldesign/PhysX.Net#34]
How to compile to mono/linux? It is possible?

**Comment by stilldesign** [comment]
To run .net code on linux it would need to be converted to .net core, but unfortunately (as far I can can tell) .net core doesn't support C++/CLI.

I have no experience with mono, so I couldn't comment on this.

**Comment by zwcloud** [comment]
Maybe it's better to rewrite PhysX.Net with C# P/Invoke instead of C++/CLI. C++/CLI has been almost abandoned by Microsoft.
