### ISSUE TITLE
UnManaged

### ISSUE THREAD

**Issue by ZtyWolfRain** [stilldesign/PhysX.Net#35]
I want to use it in Unity3D，but I failed.It is not managed

**Comment by stilldesign** [comment]
Unity already has PhysX in it.

And no this library isn't pure managed code, it wraps the native PhysX library, so it itself is a mixed .NET/native assembly.

**Comment by zwcloud** [comment]
> Unity already has PhysX in it.

Yes. But Unity doesn't provide any API about PhysX.

**Comment by stilldesign** [comment]
I've only used Unity a little bit, I'm assuming it can't load dlls that aren't purely managed code?

**Comment by zwcloud** [comment]
>  I'm assuming it can't load dlls that aren't purely managed code?

No. It can P/Invoke native code just like regular .NET applications on some platforms like Windows, Linux and Android.
