### ISSUE TITLE
Could those samples support "Any CPU"

### ISSUE THREAD

**Issue by setlin** [stilldesign/PhysX.Net#36]
Hi, Chad^_^.
I hope to use PhysX.Net for my Unity Project. For my project supports Any CPU, but all thos sample just use x64, so I can not use PhysX.Net.dll as samples.Any Help? Thanks a lot~

**Comment by stilldesign** [comment]
Unfortunately PhysX.Net only has a 64 bit version as it uses c++/cli to wrap each method as opposed to one created with PInvoke.
