### ISSUE TITLE
Release/detach of actor shapes

### ISSUE THREAD

**Issue by kpko** [stilldesign/PhysX.Net#4]
Hi, 

we need a better mechanism to support the release of shapes from actors. PhysX has its own reference counting mechanism and I think it kind of collides with the Disposing of shapes and actors how it is currently implemented.

We talked about it a few weeks ago on codeplex: https://physxdotnet.codeplex.com/workitem/35077

We have no method yet to detach a shape from an actor. This for example seems to happen automatically if we use Actor::CreateShape (see the first paragraphs of https://developer.nvidia.com/sites/default/files/akamai/physx/Docs/Shapes.html).

At one point we have to remote the object from ObjectTable too. We need a way to detect, when PhysX decides to delete the shape.

**Comment by stilldesign** [comment]
Done some work regarding attaching/detaching shapes - will close this thread and move over to: https://github.com/stilldesign/PhysX.Net/issues/10
