### ISSUE TITLE
Visual Studio 2019 for Mac issues

### ISSUE THREAD

**Issue by smlehbleh** [stilldesign/PhysX.Net#41]
Hi,
I'm using Visual Studio 2019 for mac to build a simple C# physics simulation using PhysX.Net.
I've installed the PhysX.Net C# nuget package.

After that I downloaded the PhysX library and compiled it for mac64. This generated what I believe is the necessary dynamic libraries (mac dll equivalent) for the PhysX.Net wrapper. I put these in the same folder as my VS2019 for mac project

Unfortunately when I try to run any PhysX.Net calls:
`var foundation = new PhysX.Foundation(new PhysX.ConsoleErrorCallback());`
I get this exception:
`A library name must be specified in a DllImport attribute applied to non-IJW methods.`

Do I need to specify a DllImport somewhere in my VS project? Or do I need to rebuild PhysX.Net for mac?

Thanks,
Russell

**Comment by stilldesign** [comment]
Hi,
I have never tried to get PhysX.Net to run on a mac myself. Unfortunately I doubt it will be possible as it uses .NET Framework and not the cross platform .NET Core :'( Also counting against this is that it's written in C++/CLI and for it to be cross platform would really need to be using `PInvoke` for each method.

**Comment by AndresTraks** [comment]
I reached the same conclusion when writing BulletSharp, so now there is a C++/CLI version and a PInvoke version.

You can get .NET Framework libraries running on Linux and Mac, but C++/CLI is not supported by any .NET runtime outside of Windows. Also, C++/CLI libraries are linked against the Visual C++ runtime, which is specific to Windows.
