### ISSUE TITLE
the release page of this Git is empty

### ISSUE THREAD

**Issue by ehsanwwe** [stilldesign/PhysX.Net#43]
hi
i want to try Physx.net
but when i clone the repo
i give an error like this physx.net.dll not found

**Comment by stilldesign** [comment]
The easiest way would be to use the code from one of the sample projects but install PhysX.Net from nuget

**Comment by stilldesign** [comment]
I have been meaning to create release files and add them to the releases section but have just never got round to it

**Comment by oz01** [comment]
> The easiest way would be to use the code from one of the sample projects but install PhysX.Net from nuget

i need .net5,not fx472 from nuget 😢

**Comment by stilldesign** [comment]
I've got the .net 5 package, I just haven't pushed it to NuGet yet. I'll try push this up tomorrow.

**Comment by stilldesign** [comment]
.NET 5.0 targeting package: https://www.nuget.org/packages/PhysX.Net/3.0.0-alpha1
