### ISSUE TITLE
System.BadImageFormatException: Could not load file or assembly 'PhysX.Net'

### ISSUE THREAD

**Issue by ohtrobinson** [stilldesign/PhysX.Net#44]
Hello, I get this error when I try to use PhysX. Is this my error or an error with the library?

![image](https://user-images.githubusercontent.com/52220544/111457314-f0414280-870f-11eb-9d39-ed05b9b7cd6a.png)

**Comment by stilldesign** [comment]
Make sure you've set x64 as your platform target

**Comment by stilldesign** [comment]
Are the native dll files in your output directory? They're required for PhysX itself to begin

**Comment by ohtrobinson** [comment]
Ah right, probably should have seen that - no I don't, I couldn't find them anywhere when I installed the library. I assumed they were bundled with it but I just reread the install instructions again...

Where could I find the DLLs?

**Comment by stilldesign** [comment]
They're in the package, or in `Assemblies/x64` directory of this repo.
I just noticed it looks like you've installed a really old version of the package (0.5.1), I'd use the latest version 1.0.0-alpha (pre-release). 0.5.1 is for PhysX 3 which is pretty old now and I haven't touched it in years, v1.0.0-alpha is for v4 which is the latest atm.
Version 1.0.0 of the package will also add a `.targets` file to your csproj automatically which will copy the dll files out for you.

**Comment by ohtrobinson** [comment]
Sorry for my late response.

It doesn't find the PhysX namespace at all, just gives an error.
Secondly, it tells me I need to remove this:
![image](https://user-images.githubusercontent.com/52220544/112041143-f4b99100-8b3d-11eb-9078-65bb0d05d6e0.png)
I also get an error saying "The imported project 'C:\lib\RuntimeFiles.targets' was not found."

**Comment by stilldesign** [comment]
I've just pushed up a new package which targets .NET 5: https://www.nuget.org/packages/PhysX.Net/3.0.0-alpha1
I tested creating a new console app, installing the package and setting `GeneratePathProperty` and this worked, so hopefully more luck with this version.

**Comment by ohtrobinson** [comment]
Looks like that worked. Cheers!
