### ISSUE TITLE
Detailed usage needed

### ISSUE THREAD

**Issue by beantowel** [stilldesign/PhysX.Net#47]
- How can we use the package like `using System;`, what's the namespace we should use? Or is it supposed to modify samples to use the package (btw, omnisharp in vscode reports "The type or namespace name 'Sample' could not be found (are you missing a using directive or an assembly reference?) [EventsSample]csharp(CS0246)"), the build system seems broken.
- How it works, what is the relation between PhysX.Samples.Engine and other projects in the folder. Which part of the code/repo is essential for using PhysX dll, if we were to use only a specific dll file, how can we modify the code?

**Comment by stilldesign** [comment]
Just install the package from nuget: https://www.nuget.org/packages/PhysX.Net/3.0.0-alpha1
I can only guess the reason you're receiving `The type or namespace name 'Sample' could not be found...` is thatyou'll need to be using .NET 5 (or above). .NET Core and Framework won't work.
Also make sure the nuget packages have successfully restored inside VS and the PhysX.Net reference assembly is there

Engine is just the common functionality used by the Sample, it's not needed to use PhysX.Net itself
The required files are outlined in the README.md file
If you wanted to modify the code you'd want to fork this repo and go from there
