### ISSUE TITLE
Shape already exists in object table

### ISSUE THREAD

**Issue by kpko** [stilldesign/PhysX.Net#5]
Hi!

I have a problem in my current project. Maybe this correlates with #4.

I want to clear all actors and shapes in my scene and recreate it. This functionality is used while loading other maps/files in a 3d application. But it seems like theres a duplicate object in the wrappers ObjectTable. The following exception occurs:

![image](https://cloud.githubusercontent.com/assets/835010/2983396/29796f86-dc23-11e3-986c-ba981cecf819.png)

Callstack:

![image](https://cloud.githubusercontent.com/assets/835010/2983401/4b4af6b6-dc23-11e3-96e8-a76c05711816.png)
(fyi: "Zeile" is "line" in german)

![image](https://cloud.githubusercontent.com/assets/835010/2983405/78f42ef2-dc23-11e3-9297-87284c845656.png)

Maybe someone has an idea where this errors could come from. I will try to provide a running example with a reproduction of the error.

**Comment by stilldesign** [comment]
I'm going to close this as it's quite old now, never really got round to doing anything with it unfortunately. If it's still an issue or you have reproducible example/steps/code then I'll try work through it.
